import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Aniket',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Anya',
      email: 'aniketudhane27@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'PUMA Men Typography Round Neck T-Shirt',
      slug: 'puma short sleeve t-shirt',
      category: 'T-Shirts',
      image: '/images/p6.jpg', // 679px × 829px
      price: 719,
      countInStock: 50,
      brand: 'Puma',
      rating: 4.9,
      numReviews: 9,
      description: 'Round Neck t-shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'ADIDAS Round Neck White T-Shirt',
      slug: 'adidas-fit-t-shirt',
      category: 'T-Shirts',
      image: '/images/p5.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      description: 'pure cotton product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 650,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
